export const login = 'https://i.ibb.co/47Wc5LN/a.jpg'
export const logo = '/logo.png'
export const welcome = '/welcome.svg'
export const setaesquerda = '/setaesquerda.svg'
export const cubo = '/cubo.svg'
export const avatar = './avatar.png'
